using System.Net;
using System.Net.Http.Json;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Wrapsfer.Application.Abstractions.IdentityProvisioning;
using Wrapsfer.Infrastructure.Authentication;
using Wrapsfer.Infrastructure.IdentityProvisioning.Dtos;

namespace Wrapsfer.Infrastructure.IdentityProvisioning;

internal sealed class KeycloakIntegrationClientProvisioningService : IIntegrationClientProvisioningService
{
    internal const string IntegrationRoleName = "integration_api";

    private readonly KeycloakAdminHttpClient _adminHttp;
    private readonly ILogger<KeycloakIntegrationClientProvisioningService> _logger;
    private readonly KeycloakOptions _options;

    public KeycloakIntegrationClientProvisioningService(
        KeycloakAdminHttpClient adminHttp,
        IOptions<KeycloakOptions> options,
        ILogger<KeycloakIntegrationClientProvisioningService> logger)
    {
        _adminHttp = adminHttp;
        _options = options.Value;
        _logger = logger;
    }

    internal static string BuildClientId(string tenantId) => $"wrapsfer-{tenantId}-integration";

    public async Task<IntegrationClientProvisioningResult> CreateIntegrationClientAsync(
        string tenantId,
        CancellationToken cancellationToken = default)
    {
        EnsureProvisioningEnabled();

        try
        {
            using HttpClient client = await _adminHttp.CreateAuthorizedClientAsync(cancellationToken);

            string clientId = BuildClientId(tenantId);

            await CreateIntegrationRoleAsync(client, tenantId, cancellationToken);
            string clientUuid = await CreateClientAsync(client, tenantId, clientId, cancellationToken);
            await AssignIntegrationRoleToServiceAccountAsync(client, tenantId, clientUuid, cancellationToken);

            // The secret is generated by Keycloak per client — never a shared configuration value.
            // Regenerating after creation guarantees the returned secret is the active one even
            // when an earlier partial provisioning attempt left a client behind.
            string secret = await RegenerateSecretAsync(client, tenantId, clientUuid, cancellationToken);

            return new IntegrationClientProvisioningResult(true, null, clientUuid, clientId, secret);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex,
                "Failed to provision integration client for tenant {TenantId}",
                tenantId);
            return new IntegrationClientProvisioningResult(false,
                "Provisioning request to identity provider failed");
        }
    }

    public async Task<IntegrationClientProvisioningResult> RotateIntegrationClientSecretAsync(
        string tenantId,
        string clientUuid,
        CancellationToken cancellationToken = default)
    {
        EnsureProvisioningEnabled();

        try
        {
            using HttpClient client = await _adminHttp.CreateAuthorizedClientAsync(cancellationToken);

            string secret = await RegenerateSecretAsync(client, tenantId, clientUuid, cancellationToken);

            return new IntegrationClientProvisioningResult(true, ClientUuid: clientUuid, ClientSecret: secret);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex,
                "Failed to rotate integration client secret for tenant {TenantId}",
                tenantId);
            return new IntegrationClientProvisioningResult(false,
                "Secret rotation request to identity provider failed");
        }
    }

    public async Task<IntegrationClientProvisioningResult> SetIntegrationClientEnabledAsync(
        string tenantId,
        string clientUuid,
        bool isEnabled,
        CancellationToken cancellationToken = default)
    {
        EnsureProvisioningEnabled();

        try
        {
            using HttpClient client = await _adminHttp.CreateAuthorizedClientAsync(cancellationToken);

            // PUT replaces the whole client representation, so fetch-modify-put to avoid
            // resetting flows, mappers, or scopes configured at creation time.
            HttpResponseMessage getResponse = await client.GetAsync(
                $"admin/realms/{Uri.EscapeDataString(tenantId)}/clients/{Uri.EscapeDataString(clientUuid)}",
                cancellationToken);
            await _adminHttp.EnsureSuccessAsync(getResponse,
                $"read integration client in realm {tenantId}", cancellationToken);

            KeycloakClientRepresentation? representation =
                await getResponse.Content.ReadFromJsonAsync<KeycloakClientRepresentation>(cancellationToken);

            if (representation is null)
            {
                throw new InvalidOperationException(
                    "Identity provider returned an empty integration client representation.");
            }

            representation.Enabled = isEnabled;
            representation.Secret = null;

            HttpResponseMessage putResponse = await client.PutAsJsonAsync(
                $"admin/realms/{Uri.EscapeDataString(tenantId)}/clients/{Uri.EscapeDataString(clientUuid)}",
                representation,
                cancellationToken);
            await _adminHttp.EnsureSuccessAsync(putResponse,
                $"set integration client enabled={isEnabled} in realm {tenantId}", cancellationToken);

            return new IntegrationClientProvisioningResult(true, ClientUuid: clientUuid);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex,
                "Failed to set integration client enabled={IsEnabled} for tenant {TenantId}",
                isEnabled, tenantId);
            return new IntegrationClientProvisioningResult(false,
                "Client update request to identity provider failed");
        }
    }

    public async Task<IntegrationClientProvisioningResult> DeleteIntegrationClientAsync(
        string tenantId,
        string clientUuid,
        CancellationToken cancellationToken = default)
    {
        EnsureProvisioningEnabled();

        try
        {
            using HttpClient client = await _adminHttp.CreateAuthorizedClientAsync(cancellationToken);

            HttpResponseMessage response = await client.DeleteAsync(
                $"admin/realms/{Uri.EscapeDataString(tenantId)}/clients/{Uri.EscapeDataString(clientUuid)}",
                cancellationToken);

            if (response.StatusCode is HttpStatusCode.NotFound)
            {
                return new IntegrationClientProvisioningResult(true);
            }

            await _adminHttp.EnsureSuccessAsync(response,
                $"delete integration client in realm {tenantId}", cancellationToken);

            return new IntegrationClientProvisioningResult(true);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex,
                "Failed to delete integration client for tenant {TenantId}",
                tenantId);
            return new IntegrationClientProvisioningResult(false,
                "Client delete request to identity provider failed");
        }
    }

    private void EnsureProvisioningEnabled()
    {
        if (!_options.PartnerOnboardingEnabled
            || string.IsNullOrWhiteSpace(_options.AdminClientId)
            || string.IsNullOrWhiteSpace(_options.AdminClientSecret))
        {
            throw new InvalidOperationException(
                "Partner integration provisioning is not configured. Set Keycloak:PartnerOnboardingEnabled, " +
                "Keycloak:AdminClientId, and Keycloak:AdminClientSecret.");
        }
    }

    private async Task CreateIntegrationRoleAsync(
        HttpClient client,
        string tenantId,
        CancellationToken cancellationToken)
    {
        KeycloakRoleRepresentation payload = new()
        {
            Name = IntegrationRoleName,
            Description = "Machine-to-machine partner integration role"
        };

        HttpResponseMessage response = await client.PostAsJsonAsync(
            $"admin/realms/{Uri.EscapeDataString(tenantId)}/roles",
            payload,
            cancellationToken);

        if (response.StatusCode is HttpStatusCode.Conflict)
        {
            return;
        }

        await _adminHttp.EnsureSuccessAsync(response,
            $"create role {IntegrationRoleName} in realm {tenantId}", cancellationToken);
    }

    private async Task<string> CreateClientAsync(
        HttpClient client,
        string tenantId,
        string clientId,
        CancellationToken cancellationToken)
    {
        KeycloakProtocolMapperRepresentation audienceMapper = new()
        {
            Name = "audience-mapper",
            Protocol = "openid-connect",
            ProtocolMapper = "oidc-audience-mapper",
            ConsentRequired = false,
            Config = new Dictionary<string, string>
            {
                ["included.client.audience"] = _options.Audience,
                ["id.token.claim"] = "false",
                ["access.token.claim"] = "true",
                ["introspection.token.claim"] = "true"
            }
        };

        KeycloakClientRepresentation payload = new()
        {
            ClientId = clientId,
            Name = "Wrapsfer Partner Integration",
            Enabled = true,
            PublicClient = false,
            ServiceAccountsEnabled = true,
            StandardFlowEnabled = false,
            DirectAccessGrantsEnabled = false,
            DefaultClientScopes = new List<string> { "basic", "roles" },
            ProtocolMappers = new List<KeycloakProtocolMapperRepresentation> { audienceMapper }
        };

        HttpResponseMessage response = await client.PostAsJsonAsync(
            $"admin/realms/{Uri.EscapeDataString(tenantId)}/clients",
            payload,
            cancellationToken);

        // A conflict means a previous provisioning attempt already created the client in
        // Keycloak (e.g. the metadata save failed afterwards). Reuse it instead of failing.
        if (response.StatusCode is not HttpStatusCode.Conflict)
        {
            await _adminHttp.EnsureSuccessAsync(response,
                $"create integration client in realm {tenantId}", cancellationToken);

            if (response.Headers.Location is not null)
            {
                string path = response.Headers.Location.ToString();
                int idx = path.LastIndexOf('/');
                if (idx >= 0 && idx < path.Length - 1)
                {
                    return path[(idx + 1)..];
                }
            }
        }

        return await LookupClientUuidAsync(client, tenantId, clientId, cancellationToken);
    }

    private async Task<string> LookupClientUuidAsync(
        HttpClient client,
        string tenantId,
        string clientId,
        CancellationToken cancellationToken)
    {
        HttpResponseMessage response = await client.GetAsync(
            $"admin/realms/{Uri.EscapeDataString(tenantId)}/clients?clientId={Uri.EscapeDataString(clientId)}",
            cancellationToken);

        await _adminHttp.EnsureSuccessAsync(response,
            $"lookup integration client {clientId} in realm {tenantId}", cancellationToken);

        List<KeycloakClientRepresentation>? clients =
            await response.Content.ReadFromJsonAsync<List<KeycloakClientRepresentation>>(cancellationToken);

        KeycloakClientRepresentation? representation = clients?.FirstOrDefault();
        if (representation is null || string.IsNullOrWhiteSpace(representation.Id))
        {
            throw new InvalidOperationException(
                "Identity provider did not return the integration client.");
        }

        return representation.Id;
    }

    private async Task AssignIntegrationRoleToServiceAccountAsync(
        HttpClient client,
        string tenantId,
        string clientUuid,
        CancellationToken cancellationToken)
    {
        HttpResponseMessage userResponse = await client.GetAsync(
            $"admin/realms/{Uri.EscapeDataString(tenantId)}/clients/{Uri.EscapeDataString(clientUuid)}/service-account-user",
            cancellationToken);
        await _adminHttp.EnsureSuccessAsync(userResponse,
            $"read service account user in realm {tenantId}", cancellationToken);

        KeycloakUserRepresentation? serviceAccount =
            await userResponse.Content.ReadFromJsonAsync<KeycloakUserRepresentation>(cancellationToken);

        if (serviceAccount is null || string.IsNullOrWhiteSpace(serviceAccount.Id))
        {
            throw new InvalidOperationException(
                "Identity provider did not return the integration client service account user.");
        }

        HttpResponseMessage roleResponse = await client.GetAsync(
            $"admin/realms/{Uri.EscapeDataString(tenantId)}/roles/{Uri.EscapeDataString(IntegrationRoleName)}",
            cancellationToken);
        await _adminHttp.EnsureSuccessAsync(roleResponse,
            $"read {IntegrationRoleName} role from realm {tenantId}", cancellationToken);

        KeycloakRoleRepresentation? role =
            await roleResponse.Content.ReadFromJsonAsync<KeycloakRoleRepresentation>(cancellationToken);

        if (role is null || string.IsNullOrWhiteSpace(role.Id))
        {
            throw new InvalidOperationException(
                $"Identity provider did not return the {IntegrationRoleName} role with an id.");
        }

        KeycloakRoleRepresentation[] payload = { role };

        HttpResponseMessage assignResponse = await client.PostAsJsonAsync(
            $"admin/realms/{Uri.EscapeDataString(tenantId)}/users/{Uri.EscapeDataString(serviceAccount.Id)}/role-mappings/realm",
            payload,
            cancellationToken);

        await _adminHttp.EnsureSuccessAsync(assignResponse,
            $"assign {IntegrationRoleName} role in realm {tenantId}", cancellationToken);
    }

    private async Task<string> RegenerateSecretAsync(
        HttpClient client,
        string tenantId,
        string clientUuid,
        CancellationToken cancellationToken)
    {
        HttpResponseMessage response = await client.PostAsync(
            $"admin/realms/{Uri.EscapeDataString(tenantId)}/clients/{Uri.EscapeDataString(clientUuid)}/client-secret",
            content: null,
            cancellationToken);

        await _adminHttp.EnsureSuccessAsync(response,
            $"regenerate integration client secret in realm {tenantId}", cancellationToken);

        KeycloakCredentialRepresentation? credential =
            await response.Content.ReadFromJsonAsync<KeycloakCredentialRepresentation>(cancellationToken);

        if (credential is null || string.IsNullOrWhiteSpace(credential.Value))
        {
            throw new InvalidOperationException(
                "Identity provider did not return a client secret.");
        }

        return credential.Value;
    }
}
