<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="FluentAssertions"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Moq"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
    <PackageReference Include="AWSSDK.S3"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
    <Using Include="FluentAssertions"/>
    <Using Include="Microsoft.AspNetCore.Http"/>
    <Using Include="Microsoft.Extensions.Options"/>
    <Using Include="Wrapsfer.Infrastructure.Authentication"/>
    <Using Include="Moq"/>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Wrapsfer.Application\Wrapsfer.Application.csproj"/>
    <ProjectReference Include="..\..\src\Wrapsfer.Domain\Wrapsfer.Domain.csproj"/>
    <ProjectReference Include="..\..\src\Wrapsfer.Infrastructure\Wrapsfer.Infrastructure.csproj"/>
  </ItemGroup>

</Project>